a1 = "String_operation"
print(a1.center(20, "_"))
print("="*25)
print(a1.ljust(20, "_"))
print("="*25)
x = "Mango"
print(x.zfill(10))
print("="*25)
print(x.translate(x.maketrans("M", "D")))
print("="*25)
print("The king of all fruit is", x.lstrip(), ". It is summer fruit")
print("="*25)
a = input("What is your fav color?\n")
print(a.upper(), "is a great color")
print("="*25)
b = "I am Manoj, I am a sport enthusiast"
print(b.split())
print("="*25)
c = []
d = b.split()
for a in d:
    c.append(a)
print(c)
print("="*25)
for a in c:
    for i in a:
        print(i)
print("="*25)
print(len(b))
print("="*25)
print(b.upper())
print("="*25)
print(b.lower())
if "sport" in b:
    print("We have a match for 'sport'")

print("="*25)
print("sports" in b)
print("="*25)
print(b[:11], "\n", b[12:], "\nIn reverse:\n", b[::-1], "\n", b[1::1])
print("="*25)
print(b.replace(" ", "-"))
print("="*25)
print(b.startswith("I"))
print("="*25)
print(b.endswith("."))
print("="*25)
print(b.center(20, "0"))
print("="*25)
f = b.lower()
print(f, "#is lower case...so\n", f.islower())
print("="*25)
print(f.capitalize())
print("="*25)
print(b.casefold())
print("="*25)
print("I: ", b.count("I" or "i"), "\nA:", b.count("a"))
print("="*25)
b1 = "Я\tМаной,\tя\tспортивный\tэнтузиаст"
print(b1.encode())
print("="*25)
print(b1.expandtabs())
print("="*25)
print(b.index("Manoj", 0, 10))
print("="*25)
print(b.find("j"))
print("="*25)
c1 = ('I', 'am', 'human')
print(" ".join(c1))
print("="*25)
b2 = "I am Manoj,\n I am a sport Enthusiast"
print("swapcase: ", b2.swapcase())
print("="*25)
print("split_line: ", b2.splitlines(True))
print("="*25)
print(a1.rjust(20), b)
print("="*25)
print("index", b.rindex("sport"))
print("="*25)
print("rfind:", b.rfind("t", 0, 28))
print("="*25)
print("Partition:", b.partition("Manoj"))
print("="*25)
print("Replacing:", b.replace("Manoj", "Ussain_Bolt"))
print("="*25)
print("string in uppercase", b.isupper())
print("="*25)
print("is uppercase at start", b.istitle())
print("="*25)
print("all character are whitespace?", b.isspace())
print("="*25)
print("Alpha numeric? : ", b.isalnum())
print("="*25)
print("Alpha? : ", b.isalpha())
print("="*25)
print("ascii? : ", b.isascii())
print("="*25)
print("Identifier:", b.isidentifier())
print("="*25)
print("printable:", b.isprintable())
print("="*25)
